"""empty message

Revision ID: 174b0b421862
Revises: 77bddf113c56
Create Date: 2019-05-19 09:05:36.422874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174b0b421862'
down_revision = '77bddf113c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'title',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
