"""empty message

Revision ID: 68577bdf1f7b
Revises: 174b0b421862
Create Date: 2019-05-19 09:22:47.279248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68577bdf1f7b'
down_revision = '174b0b421862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=300),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'title',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###
