"""empty message

Revision ID: 77bddf113c56
Revises: 5982d686bb3b
Create Date: 2019-05-12 12:06:06.053371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77bddf113c56'
down_revision = '5982d686bb3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_cat',
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('cat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['cat_id'], ['categories.id'], )
    )
    op.drop_column('books', 'categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('categories', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_table('book_cat')
    op.drop_table('categories')
    # ### end Alembic commands ###
